# Generated by Django 5.2.16 on 2026-07-13 00:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockPrendaModel',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('prenda_id', models.CharField(max_length=36)),
                ('cantidad_actual', models.IntegerField()),
                ('nivel_minimo', models.IntegerField()),
                ('ubicacion', models.CharField(default='almacen', max_length=120)),
                ('unidad', models.CharField(default='unidad', max_length=30)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'stocks_prenda',
                'unique_together': {('prenda_id',)},
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventarioModel',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=30)),
                ('cantidad', models.IntegerField()),
                ('motivo', models.TextField()),
                ('registrado_por', models.CharField(max_length=36)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='inventario.stockprendamodel')),
            ],
            options={
                'db_table': 'movimientos_inventario',
            },
        ),
        migrations.CreateModel(
            name='AlertaStockModel',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('nivel_actual', models.IntegerField()),
                ('nivel_minimo', models.IntegerField()),
                ('estado', models.CharField(default='pendiente', max_length=30)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='inventario.stockprendamodel')),
            ],
            options={
                'db_table': 'alertas_stock',
            },
        ),
    ]
