# Generated by Django 5.2.16 on 2026-07-27 06:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockVarianteModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad_actual', models.IntegerField(default=0)),
                ('cantidad_reservada', models.IntegerField(default=0)),
                ('nivel_minimo', models.IntegerField(default=0)),
                ('ubicacion', models.CharField(default='almacen', max_length=120)),
                ('unidad', models.CharField(default='unidad', max_length=30)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('variante', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='stock', to='catalogo.varianteprendamodel')),
            ],
            options={
                'db_table': 'stocks_variante',
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventarioModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('ingreso', 'ingreso'), ('salida', 'salida'), ('ajuste', 'ajuste')], default='ingreso', max_length=30)),
                ('cantidad', models.IntegerField()),
                ('motivo', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_registrados', to='usuarios.usuariomodel')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='inventario.stockvariantemodel')),
            ],
            options={
                'db_table': 'movimientos_inventario',
            },
        ),
        migrations.CreateModel(
            name='AlertaStockModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nivel_actual', models.IntegerField()),
                ('nivel_minimo', models.IntegerField()),
                ('estado', models.CharField(choices=[('pendiente', 'pendiente'), ('atendida', 'atendida')], default='pendiente', max_length=30)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='inventario.stockvariantemodel')),
            ],
            options={
                'db_table': 'alertas_stock',
            },
        ),
        migrations.AddIndex(
            model_name='stockvariantemodel',
            index=models.Index(fields=['ubicacion'], name='stock_ubicacion_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockvariantemodel',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad_actual__gte', 0)), name='stock_cantidad_no_negativa'),
        ),
        migrations.AddConstraint(
            model_name='stockvariantemodel',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad_reservada__gte', 0)), name='stock_reservada_no_negativa'),
        ),
        migrations.AddConstraint(
            model_name='stockvariantemodel',
            constraint=models.CheckConstraint(condition=models.Q(('nivel_minimo__gte', 0)), name='stock_nivel_minimo_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='stockvariantemodel',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad_reservada__lte', models.F('cantidad_actual'))), name='stock_reservada_no_excede_actual'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventariomodel',
            index=models.Index(fields=['stock', '-fecha'], name='movimiento_stock_fecha_idx'),
        ),
        migrations.AddConstraint(
            model_name='movimientoinventariomodel',
            constraint=models.CheckConstraint(condition=models.Q(('tipo__in', ['ingreso', 'salida', 'ajuste'])), name='movimiento_tipo_valido'),
        ),
        migrations.AddConstraint(
            model_name='movimientoinventariomodel',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='movimiento_cantidad_positiva'),
        ),
        migrations.AddConstraint(
            model_name='alertastockmodel',
            constraint=models.CheckConstraint(condition=models.Q(('estado__in', ['pendiente', 'atendida'])), name='alerta_estado_valido'),
        ),
        migrations.AddConstraint(
            model_name='alertastockmodel',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'pendiente')), fields=('stock',), name='alerta_pendiente_unica_por_stock'),
        ),
    ]
