# Generated by Django 5.2.16 on 2026-07-23 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="stockprendamodel",
            constraint=models.CheckConstraint(
                condition=models.Q(("cantidad_actual__gte", 0)),
                name="stock_cantidad_actual_no_negativa",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockprendamodel",
            constraint=models.CheckConstraint(
                condition=models.Q(("nivel_minimo__gte", 0)),
                name="stock_nivel_minimo_no_negativo",
            ),
        ),
    ]
