# Generated by Django 5.2.16 on 2026-07-13 00:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaModel',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField(default='')),
            ],
            options={
                'db_table': 'categorias',
            },
        ),
        migrations.CreateModel(
            name='TipoProductoModel',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
                ('atributos_base', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'tipos_producto',
            },
        ),
        migrations.CreateModel(
            name='PrendaModel',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField(default='')),
                ('precio_monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio_moneda', models.CharField(default='PEN', max_length=3)),
                ('estado', models.CharField(default='activa', max_length=30)),
                ('registrado_por', models.CharField(blank=True, max_length=36, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.categoriamodel')),
                ('tipo_producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.tipoproductomodel')),
            ],
            options={
                'db_table': 'prendas',
            },
        ),
    ]
