# Generated by Django 5.2.16 on 2026-07-27 06:07

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField(default='')),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'categorias',
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('nombre'), name='categoria_nombre_unico_ci')],
            },
        ),
        migrations.CreateModel(
            name='TipoProductoModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
                ('atributos_base', models.JSONField(default=dict)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tipos_producto',
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('nombre'), name='tipo_producto_nombre_unico_ci')],
            },
        ),
        migrations.CreateModel(
            name='PrendaModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField(default='')),
                ('precio_monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio_moneda', models.CharField(choices=[('PEN', 'PEN'), ('USD', 'USD')], default='PEN', max_length=3)),
                ('estado', models.CharField(choices=[('activa', 'activa'), ('inactiva', 'inactiva')], default='activa', max_length=30)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prendas', to='catalogo.categoriamodel')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prendas_registradas', to='usuarios.usuariomodel')),
                ('tipo_producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prendas', to='catalogo.tipoproductomodel')),
            ],
            options={
                'db_table': 'prendas',
            },
        ),
        migrations.CreateModel(
            name='VariantePrendaModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=60, unique=True)),
                ('talla', models.CharField(max_length=20)),
                ('color', models.CharField(default='', max_length=40)),
                ('precio_monto', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('precio_moneda', models.CharField(blank=True, choices=[('PEN', 'PEN'), ('USD', 'USD')], default='PEN', max_length=3, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('prenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='catalogo.prendamodel')),
            ],
            options={
                'db_table': 'variantes_prenda',
            },
        ),
        migrations.AddIndex(
            model_name='prendamodel',
            index=models.Index(fields=['categoria'], name='prenda_categoria_idx'),
        ),
        migrations.AddIndex(
            model_name='prendamodel',
            index=models.Index(condition=models.Q(('estado', 'activa')), fields=['nombre'], name='prenda_activa_nombre_idx'),
        ),
        migrations.AddConstraint(
            model_name='prendamodel',
            constraint=models.CheckConstraint(condition=models.Q(('estado__in', ['activa', 'inactiva'])), name='prenda_estado_valido'),
        ),
        migrations.AddConstraint(
            model_name='prendamodel',
            constraint=models.CheckConstraint(condition=models.Q(('precio_monto__gt', Decimal('0'))), name='prenda_precio_positivo'),
        ),
        migrations.AddIndex(
            model_name='varianteprendamodel',
            index=models.Index(fields=['prenda'], name='variante_prenda_idx'),
        ),
        migrations.AddConstraint(
            model_name='varianteprendamodel',
            constraint=models.UniqueConstraint(fields=('prenda', 'talla', 'color'), name='variante_combinacion_unica'),
        ),
        migrations.AddConstraint(
            model_name='varianteprendamodel',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('precio_moneda__isnull', True), ('precio_monto__isnull', True)), models.Q(('precio_moneda__isnull', False), ('precio_monto__gt', 0)), _connector='OR'), name='variante_precio_completo'),
        ),
    ]
