# Generated by Django 5.2.16 on 2026-07-27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalogo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="prendamodel",
            name="imagen",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="catalogo/",
            ),
        ),
        migrations.AlterField(
            model_name="varianteprendamodel",
            name="precio_moneda",
            field=models.CharField(
                blank=True,
                choices=[("PEN", "PEN"), ("USD", "USD")],
                default=None,
                max_length=3,
                null=True,
            ),
        ),
    ]
