# Generated by Django 5.2.16 on 2026-07-13 00:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntentoLoginModel',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=120)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('ip', models.CharField(default='', max_length=60)),
                ('exitoso', models.BooleanField(default=False)),
                ('motivo_fallo', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'db_table': 'intentos_login',
            },
        ),
        migrations.CreateModel(
            name='RolModel',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField(default='')),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='UsuarioModel',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=160, unique=True)),
                ('estado', models.CharField(default='activo', max_length=30)),
                ('username', models.CharField(default='', max_length=120, unique=True)),
                ('password_hash', models.CharField(default='', max_length=255)),
                ('creado_por', models.CharField(blank=True, max_length=36, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.rolmodel')),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='SesionModel',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_expiracion', models.DateTimeField(blank=True, null=True)),
                ('ip', models.CharField(default='', max_length=60)),
                ('estado', models.CharField(default='activa', max_length=30)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuariomodel')),
            ],
            options={
                'db_table': 'sesiones',
            },
        ),
    ]
