# Generated by Django 5.2.16 on 2026-07-27 06:07

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RolModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField(default='')),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='IntentoLoginModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=120)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('exitoso', models.BooleanField(default=False)),
                ('motivo_fallo', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'db_table': 'intentos_login',
                'indexes': [models.Index(fields=['username', '-fecha'], name='intento_usuario_fecha_idx')],
            },
        ),
        migrations.CreateModel(
            name='PermisoModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=120, unique=True)),
                ('descripcion', models.TextField(default='')),
                ('modulo', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'permisos',
                'indexes': [models.Index(fields=['modulo'], name='permiso_modulo_idx')],
            },
        ),
        migrations.CreateModel(
            name='RolPermisoModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('permiso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='usuarios.permisomodel')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='usuarios.rolmodel')),
            ],
            options={
                'db_table': 'roles_permisos',
            },
        ),
        migrations.AddField(
            model_name='rolmodel',
            name='permisos',
            field=models.ManyToManyField(related_name='roles', through='usuarios.RolPermisoModel', to='usuarios.permisomodel'),
        ),
        migrations.CreateModel(
            name='UsuarioModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=160)),
                ('username', models.CharField(max_length=120)),
                ('estado', models.CharField(choices=[('activo', 'activo'), ('inactivo', 'inactivo')], default='activo', max_length=30)),
                ('password_hash', models.CharField(default='', max_length=255)),
                ('password_salt', models.CharField(default='', max_length=64)),
                ('password_algoritmo', models.CharField(default='werkzeug-pbkdf2', max_length=60)),
                ('password_actualizado_en', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_creados', to='usuarios.usuariomodel')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='usuarios.rolmodel')),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='SesionModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_expiracion', models.DateTimeField()),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('activa', 'activa'), ('expirada', 'expirada'), ('cerrada', 'cerrada')], default='activa', max_length=30)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='usuarios.usuariomodel')),
            ],
            options={
                'db_table': 'sesiones',
            },
        ),
        migrations.AddConstraint(
            model_name='rolpermisomodel',
            constraint=models.UniqueConstraint(fields=('rol', 'permiso'), name='rol_permiso_unico'),
        ),
        migrations.AddConstraint(
            model_name='rolmodel',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('nombre'), name='rol_nombre_unico_ci'),
        ),
        migrations.AddIndex(
            model_name='usuariomodel',
            index=models.Index(fields=['estado'], name='usuario_estado_idx'),
        ),
        migrations.AddIndex(
            model_name='usuariomodel',
            index=models.Index(fields=['rol'], name='usuario_rol_idx'),
        ),
        migrations.AddConstraint(
            model_name='usuariomodel',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='usuario_email_unico_ci'),
        ),
        migrations.AddConstraint(
            model_name='usuariomodel',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('username'), name='usuario_username_unico_ci'),
        ),
        migrations.AddConstraint(
            model_name='usuariomodel',
            constraint=models.CheckConstraint(condition=models.Q(('estado__in', ['activo', 'inactivo'])), name='usuario_estado_valido'),
        ),
        migrations.AddIndex(
            model_name='sesionmodel',
            index=models.Index(condition=models.Q(('estado', 'activa')), fields=['usuario'], name='sesion_activa_usuario_idx'),
        ),
        migrations.AddIndex(
            model_name='sesionmodel',
            index=models.Index(fields=['fecha_expiracion'], name='sesion_expira_idx'),
        ),
        migrations.AddConstraint(
            model_name='sesionmodel',
            constraint=models.CheckConstraint(condition=models.Q(('estado__in', ['activa', 'expirada', 'cerrada'])), name='sesion_estado_valido'),
        ),
        migrations.AddConstraint(
            model_name='sesionmodel',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_expiracion__gt', models.F('fecha_inicio'))), name='sesion_expiracion_posterior_al_inicio'),
        ),
    ]
