# Generated by Django 5.2.16 on 2026-07-27 06:07

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarritoModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('abierto', 'abierto'), ('convertido', 'convertido'), ('cancelado', 'cancelado')], default='abierto', max_length=30)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='carritos', to='usuarios.usuariomodel')),
            ],
            options={
                'db_table': 'carritos',
            },
        ),
        migrations.CreateModel(
            name='DespachoModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direccion_entrega', models.CharField(max_length=250)),
                ('estado', models.CharField(choices=[('pendiente', 'pendiente'), ('preparado', 'preparado'), ('confirmado', 'confirmado'), ('cancelado', 'cancelado')], default='pendiente', max_length=30)),
                ('fecha_preparacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despachos_atendidos', to='usuarios.usuariomodel')),
            ],
            options={
                'db_table': 'despachos',
            },
        ),
        migrations.CreateModel(
            name='GuiaRemisionModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('serie', models.CharField(max_length=10)),
                ('numero', models.CharField(max_length=20)),
                ('transportista', models.CharField(default='', max_length=120)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('despacho', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guia', to='ventas.despachomodel')),
            ],
            options={
                'db_table': 'guias_remision',
            },
        ),
        migrations.CreateModel(
            name='ItemCarritoModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio_monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio_moneda', models.CharField(choices=[('PEN', 'PEN'), ('USD', 'USD')], default='PEN', max_length=3)),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ventas.carritomodel')),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items_carrito', to='catalogo.varianteprendamodel')),
            ],
            options={
                'db_table': 'items_carrito',
            },
        ),
        migrations.CreateModel(
            name='PedidoModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_moneda', models.CharField(choices=[('PEN', 'PEN'), ('USD', 'USD')], default='PEN', max_length=3)),
                ('estado', models.CharField(choices=[('creado', 'creado'), ('pagado', 'pagado'), ('cancelado', 'cancelado')], default='creado', max_length=30)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('carrito', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='pedido', to='ventas.carritomodel')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='usuarios.usuariomodel')),
            ],
            options={
                'db_table': 'pedidos',
            },
        ),
        migrations.CreateModel(
            name='PagoModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('monto_monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monto_moneda', models.CharField(choices=[('PEN', 'PEN'), ('USD', 'USD')], default='PEN', max_length=3)),
                ('metodo', models.CharField(choices=[('efectivo', 'efectivo'), ('tarjeta', 'tarjeta'), ('transferencia', 'transferencia'), ('yape', 'yape')], default='efectivo', max_length=30)),
                ('referencia', models.CharField(default='', max_length=120)),
                ('estado', models.CharField(choices=[('pendiente', 'pendiente'), ('aprobado', 'aprobado'), ('rechazado', 'rechazado')], default='pendiente', max_length=30)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pago', to='ventas.pedidomodel')),
            ],
            options={
                'db_table': 'pagos',
            },
        ),
        migrations.CreateModel(
            name='DetallePedidoModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio_monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio_moneda', models.CharField(choices=[('PEN', 'PEN'), ('USD', 'USD')], default='PEN', max_length=3)),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_pedido', to='catalogo.varianteprendamodel')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas.pedidomodel')),
            ],
            options={
                'db_table': 'detalles_pedido',
            },
        ),
        migrations.AddField(
            model_name='despachomodel',
            name='pedido',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='despacho', to='ventas.pedidomodel'),
        ),
        migrations.AddConstraint(
            model_name='carritomodel',
            constraint=models.CheckConstraint(condition=models.Q(('estado__in', ['abierto', 'convertido', 'cancelado'])), name='carrito_estado_valido'),
        ),
        migrations.AddConstraint(
            model_name='carritomodel',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'abierto')), fields=('cliente',), name='carrito_abierto_unico_por_cliente'),
        ),
        migrations.AddConstraint(
            model_name='guiaremisionmodel',
            constraint=models.UniqueConstraint(fields=('serie', 'numero'), name='guia_serie_numero_unica'),
        ),
        migrations.AddConstraint(
            model_name='itemcarritomodel',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='item_carrito_cantidad_positiva'),
        ),
        migrations.AddConstraint(
            model_name='itemcarritomodel',
            constraint=models.CheckConstraint(condition=models.Q(('precio_monto__gt', Decimal('0'))), name='item_carrito_precio_positivo'),
        ),
        migrations.AddConstraint(
            model_name='itemcarritomodel',
            constraint=models.UniqueConstraint(fields=('carrito', 'variante'), name='item_carrito_variante_unica'),
        ),
        migrations.AddIndex(
            model_name='pedidomodel',
            index=models.Index(fields=['cliente', '-fecha_creacion'], name='pedido_cliente_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='pedidomodel',
            index=models.Index(fields=['estado'], name='pedido_estado_idx'),
        ),
        migrations.AddConstraint(
            model_name='pedidomodel',
            constraint=models.CheckConstraint(condition=models.Q(('estado__in', ['creado', 'pagado', 'cancelado'])), name='pedido_estado_valido'),
        ),
        migrations.AddConstraint(
            model_name='pedidomodel',
            constraint=models.CheckConstraint(condition=models.Q(('total_monto__gt', Decimal('0'))), name='pedido_total_positivo'),
        ),
        migrations.AddIndex(
            model_name='pagomodel',
            index=models.Index(fields=['fecha', 'id'], name='pago_fecha_id_idx'),
        ),
        migrations.AddConstraint(
            model_name='pagomodel',
            constraint=models.UniqueConstraint(fields=('pedido',), name='pago_pedido_unico'),
        ),
        migrations.AddConstraint(
            model_name='pagomodel',
            constraint=models.CheckConstraint(condition=models.Q(('monto_monto__gt', Decimal('0'))), name='pago_monto_positivo'),
        ),
        migrations.AddConstraint(
            model_name='pagomodel',
            constraint=models.CheckConstraint(condition=models.Q(('estado__in', ['pendiente', 'aprobado', 'rechazado'])), name='pago_estado_valido'),
        ),
        migrations.AddConstraint(
            model_name='pagomodel',
            constraint=models.CheckConstraint(condition=models.Q(('metodo__in', ['efectivo', 'tarjeta', 'transferencia', 'yape'])), name='pago_metodo_valido'),
        ),
        migrations.AddConstraint(
            model_name='pagomodel',
            constraint=models.CheckConstraint(condition=models.Q(('metodo', 'efectivo'), models.Q(('referencia', ''), _negated=True), _connector='OR'), name='pago_referencia_requerida'),
        ),
        migrations.AddConstraint(
            model_name='detallepedidomodel',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='detalle_pedido_cantidad_positiva'),
        ),
        migrations.AddConstraint(
            model_name='detallepedidomodel',
            constraint=models.CheckConstraint(condition=models.Q(('precio_monto__gt', Decimal('0'))), name='detalle_pedido_precio_positivo'),
        ),
        migrations.AddConstraint(
            model_name='detallepedidomodel',
            constraint=models.UniqueConstraint(fields=('pedido', 'variante'), name='detalle_pedido_variante_unica'),
        ),
        migrations.AddIndex(
            model_name='despachomodel',
            index=models.Index(fields=['estado'], name='despacho_estado_idx'),
        ),
        migrations.AddConstraint(
            model_name='despachomodel',
            constraint=models.CheckConstraint(condition=models.Q(('estado__in', ['pendiente', 'preparado', 'confirmado', 'cancelado'])), name='despacho_estado_valido'),
        ),
        migrations.AddConstraint(
            model_name='despachomodel',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('estado', 'confirmado'), _negated=True), ('fecha_confirmacion__isnull', False), _connector='OR'), name='despacho_confirmado_con_fecha'),
        ),
    ]
