# Generated by Django 5.2.16 on 2026-07-13 00:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarritoModel',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('cliente_id', models.CharField(max_length=36)),
                ('estado', models.CharField(default='abierto', max_length=30)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'carritos',
            },
        ),
        migrations.CreateModel(
            name='PagoModel',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('pedido_id', models.CharField(max_length=36)),
                ('monto_monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monto_moneda', models.CharField(default='PEN', max_length=3)),
                ('metodo', models.CharField(max_length=30)),
                ('referencia', models.CharField(default='', max_length=120)),
                ('estado', models.CharField(default='pendiente', max_length=30)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'pagos',
            },
        ),
        migrations.CreateModel(
            name='PedidoModel',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('cliente_id', models.CharField(max_length=36)),
                ('carrito_id', models.CharField(max_length=36)),
                ('total_monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_moneda', models.CharField(default='PEN', max_length=3)),
                ('estado', models.CharField(default='creado', max_length=30)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'pedidos',
            },
        ),
        migrations.CreateModel(
            name='ItemCarritoModel',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('prenda_id', models.CharField(max_length=36)),
                ('cantidad', models.IntegerField()),
                ('precio_monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio_moneda', models.CharField(default='PEN', max_length=3)),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ventas.carritomodel')),
            ],
            options={
                'db_table': 'items_carrito',
            },
        ),
        migrations.CreateModel(
            name='DetallePedidoModel',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('prenda_id', models.CharField(max_length=36)),
                ('cantidad', models.IntegerField()),
                ('precio_monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio_moneda', models.CharField(default='PEN', max_length=3)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas.pedidomodel')),
            ],
            options={
                'db_table': 'detalles_pedido',
            },
        ),
    ]
